# Generated by Powerlevel10k configuration wizard on 2026-03-25 at 20:39 CST.
# Based on romkatv/powerlevel10k/config/p10k-rainbow.zsh, checksum 57633.
# Wizard options: nerdfont-v3 + powerline, large icons, rainbow, unicode, 12h time,
# vertical separators, round heads, round tails, 2 lines, disconnected, no frame,
# sparse, few icons, concise, transient_prompt, instant_prompt=quiet.
# Type `p10k configure` to generate another config.
#
# Config for Powerlevel10k with powerline prompt style with colorful background.
# Type `p10k configure` to generate your own config based on it.
#
# Tip: Looking for a nice color? Here's a one-liner to print colormap.
#
#   for i in {0..255}; do print -Pn "%K{$i}  %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%6)):#3}:+$'\n'}; done

# Temporarily change options.
'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh -o extended_glob

  # Unset all configuration options. This allows you to apply configuration changes without
  # restarting zsh. Edit ~/.p10k.zsh and type `source ~/.p10k.zsh`.
  unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'

  # Zsh >= 5.1 is required.
  [[ $ZSH_VERSION == (5.<1->*|<6->.*) ]] || return

  # Gruvbox Dark Palette Definitions
  local fg0='#fbf1c7'
  local bg1='#3c3836'
  local bg3='#665c54'
  local blue='#458588'
  local aqua='#689d6a'
  local green='#98971a'
  local orange='#d65d0e'
  local purple='#b16286'
  local red='#cc241d'
  local yellow='#d79921'

  # The list of segments shown on the left. Fill it with the most important segments.
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    # =========================[ Line #1 ]=========================
    os_icon                 # os identifier
    context                 # user
    dir                     # current directory
    vcs                     # git status
    c                       # c version
    cpp                     # cpp version
    rust_version            # rust version
    go_version              # go version
    node_version            # nodejs version
    php_version             # php version
    java_version            # java version
    kotlin_version          # kotlin version
    haskell_stack           # haskell version
    python                  # python (asdf/pyenv)
    docker_context          # docker context
    anaconda                # conda environment
    time                    # current time
    # =========================[ Line #2 ]=========================
    newline                 # \n
    prompt_char             # prompt symbol
  )

  # The list of segments shown on the right. Fill it with less important segments.
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()

  # Defines character set used by powerlevel10k. It's best to let `p10k configure` set it for you.
  typeset -g POWERLEVEL9K_MODE=nerdfont-v3
  # When set to `moderate`, some icons will have an extra space after them. This is meant to avoid
  # icon overlap when using non-monospace fonts. When set to `none`, spaces are not added.
  typeset -g POWERLEVEL9K_ICON_PADDING=moderate

  # When set to true, icons appear before content on both sides of the prompt.
  typeset -g POWERLEVEL9K_ICON_BEFORE_CONTENT=true

  # Add an empty line before each prompt.
  typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=
  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX=
  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_SUFFIX=
  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_SUFFIX=
  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_SUFFIX=

  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR=' '
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_BACKGROUND=
  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_GAP_BACKGROUND=
  if [[ $POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR != ' ' ]]; then
    typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_FOREGROUND=242
    typeset -g POWERLEVEL9K_EMPTY_LINE_LEFT_PROMPT_FIRST_SEGMENT_END_SYMBOL='%{%}'
    typeset -g POWERLEVEL9K_EMPTY_LINE_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='%{%}'
  fi

  # Style matches Starship separators
  typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=' '
  typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=' '
  typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\uE0B0'
  typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\uE0B2'

  typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL='\uE0B4 '
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='\uE0B6'
  typeset -g POWERLEVEL9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL='\uE0B6'
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL='\uE0B4'
  typeset -g POWERLEVEL9K_EMPTY_LINE_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=

  #################################[ os_icon: os identifier ]##################################
  typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=$fg0
  typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND=$orange
  
  # Custom OS symbols matching Starship
  typeset -g POWERLEVEL9K_OS_ICON_WINDOWS_CONTENT_EXPANSION="󰍲"
  typeset -g POWERLEVEL9K_OS_ICON_UBUNTU_CONTENT_EXPANSION="󰕈"
  typeset -g POWERLEVEL9K_OS_ICON_SUSE_CONTENT_EXPANSION=""
  typeset -g POWERLEVEL9K_OS_ICON_RASPBIAN_CONTENT_EXPANSION="󰐿"
  typeset -g POWERLEVEL9K_OS_ICON_MINT_CONTENT_EXPANSION="󰣭"
  typeset -g POWERLEVEL9K_OS_ICON_MACOS_CONTENT_EXPANSION="󰀵"
  typeset -g POWERLEVEL9K_OS_ICON_MANJARO_CONTENT_EXPANSION=""
  typeset -g POWERLEVEL9K_OS_ICON_LINUX_CONTENT_EXPANSION="󰌽"
  typeset -g POWERLEVEL9K_OS_ICON_GENTOO_CONTENT_EXPANSION="󰣨"
  typeset -g POWERLEVEL9K_OS_ICON_FEDORA_CONTENT_EXPANSION="󰣛"
  typeset -g POWERLEVEL9K_OS_ICON_ALPINE_CONTENT_EXPANSION=""
  typeset -g POWERLEVEL9K_OS_ICON_AMAZON_CONTENT_EXPANSION=""
  typeset -g POWERLEVEL9K_OS_ICON_ANDROID_CONTENT_EXPANSION=""
  typeset -g POWERLEVEL9K_OS_ICON_AOSC_CONTENT_EXPANSION=""
  typeset -g POWERLEVEL9K_OS_ICON_ARCH_CONTENT_EXPANSION="󰣇"
  typeset -g POWERLEVEL9K_OS_ICON_ARTIX_CONTENT_EXPANSION="󰣇"
  typeset -g POWERLEVEL9K_OS_ICON_ENDEAVOUROS_CONTENT_EXPANSION=""
  typeset -g POWERLEVEL9K_OS_ICON_CENTOS_CONTENT_EXPANSION=""
  typeset -g POWERLEVEL9K_OS_ICON_DEBIAN_CONTENT_EXPANSION="󰣚"
  typeset -g POWERLEVEL9K_OS_ICON_REDHAT_CONTENT_EXPANSION="󱄛"
  typeset -g POWERLEVEL9K_OS_ICON_POP_CONTENT_EXPANSION=""

  ##################################[ context: user@hostname ]##################################
  typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=$fg0
  typeset -g POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND=$orange
  typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_FOREGROUND=$fg0
  typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_BACKGROUND=$orange
  typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND=$fg0
  typeset -g POWERLEVEL9K_CONTEXT_BACKGROUND=$orange
  typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE=' %n '
  typeset -g POWERLEVEL9K_CONTEXT_ROOT_TEMPLATE=' %n '
  typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_TEMPLATE=' %n '
  # Always show context
  typeset -g POWERLEVEL9K_CONTEXT_{DEFAULT,SUDO}_{CONTENT,VISUAL_IDENTIFIER}_EXPANSION=

  ################################[ prompt_char: prompt symbol ]################################
  typeset -g POWERLEVEL9K_PROMPT_CHAR_BACKGROUND=
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=$green
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=$red
  
  # Matching Starship characters
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION=''
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VICMD_CONTENT_EXPANSION=''
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIVIS_CONTENT_EXPANSION='%F{'$yellow'}%f'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIOWR_CONTENT_EXPANSION='%F{'$purple'}%f'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OVERWRITE_STATE=true
  typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=
  typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=
  typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_{LEFT,RIGHT}_WHITESPACE=

  ##################################[ dir: current directory ]##################################
  typeset -g POWERLEVEL9K_DIR_BACKGROUND=$yellow
  typeset -g POWERLEVEL9K_DIR_FOREGROUND=$fg0
  typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
  typeset -g POWERLEVEL9K_SHORTEN_DELIMITER="…/"
  typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=$fg0
  typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=$fg0
  typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=false
  local anchor_files=(
    .bzr .citc .git .hg .node-version .python-version .go-version .ruby-version .lua-version
    .java-version .perl-version .php-version .tool-versions .mise.toml .shorten_folder_marker
    .svn .terraform CVS Cargo.toml composer.json go.mod package.json stack.yaml
  )
  typeset -g POWERLEVEL9K_SHORTEN_FOLDER_MARKER="(${(j:|:)anchor_files})"
  typeset -g POWERLEVEL9K_DIR_TRUNCATE_BEFORE_MARKER=false
  typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=3 # truncating length 3
  typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=80
  typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS=40
  typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS_PCT=50
  typeset -g POWERLEVEL9K_DIR_HYPERLINK=false
  typeset -g POWERLEVEL9K_DIR_SHOW_WRITABLE=v3

  # Directory substitutions
  typeset -g POWERLEVEL9K_DIR_CLASSES=(
    '*(Documents)'   DOCUMENTS ''
    '*(Downloads)'   DOWNLOADS ''
    '*(Music)'       MUSIC     ''
    '*(Pictures)'    PICTURES  ''
    '*(Developer)'   DEVELOPER ''
  )
  typeset -g POWERLEVEL9K_DIR_DOCUMENTS_VISUAL_IDENTIFIER_EXPANSION='󰈙'
  typeset -g POWERLEVEL9K_DIR_DOWNLOADS_VISUAL_IDENTIFIER_EXPANSION=''
  typeset -g POWERLEVEL9K_DIR_MUSIC_VISUAL_IDENTIFIER_EXPANSION='󰝚'
  typeset -g POWERLEVEL9K_DIR_PICTURES_VISUAL_IDENTIFIER_EXPANSION=''
  typeset -g POWERLEVEL9K_DIR_DEVELOPER_VISUAL_IDENTIFIER_EXPANSION='󰲋'

  #####################################[ vcs: git status ]######################################
  typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND=$aqua
  typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=$aqua
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=$aqua
  typeset -g POWERLEVEL9K_VCS_CONFLICTED_BACKGROUND=$aqua
  typeset -g POWERLEVEL9K_VCS_LOADING_BACKGROUND=$aqua
  
  typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=$fg0
  typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=$fg0
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=$fg0
  typeset -g POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND=$fg0

  typeset -g POWERLEVEL9K_VCS_BRANCH_ICON=''
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON='?'

  function my_git_formatter() {
    emulate -L zsh

    if [[ -n $P9K_CONTENT ]]; then
      typeset -g my_git_format=$P9K_CONTENT
      return
    fi

    local       meta='%F{'$fg0'}' 
    local      clean='%F{'$fg0'}' 
    local   modified='%F{'$fg0'}' 
    local  untracked='%F{'$fg0'}' 
    local conflicted='%F{'$fg0'}' 

    local res

    if [[ -n $VCS_STATUS_LOCAL_BRANCH ]]; then
      local branch=${(V)VCS_STATUS_LOCAL_BRANCH}
      (( $#branch > 32 )) && branch[13,-13]="…" 
      res+="${clean}${(g::)POWERLEVEL9K_VCS_BRANCH_ICON} ${branch//\%/%%}"
    fi

    if [[ -n $VCS_STATUS_TAG && -z $VCS_STATUS_LOCAL_BRANCH ]]; then
      local tag=${(V)VCS_STATUS_TAG}
      (( $#tag > 32 )) && tag[13,-13]="…" 
      res+="${meta}#${clean}${tag//\%/%%}"
    fi

    [[ -z $VCS_STATUS_LOCAL_BRANCH && -z $VCS_STATUS_TAG ]] && 
      res+="${meta}@${clean}${VCS_STATUS_COMMIT[1,8]}"

    if [[ -n ${VCS_STATUS_REMOTE_BRANCH:#$VCS_STATUS_LOCAL_BRANCH} ]]; then
      res+="${meta}:${clean}${(V)VCS_STATUS_REMOTE_BRANCH//\%/%%}"
    fi

    if [[ $VCS_STATUS_COMMIT_SUMMARY == (|*[^[:alnum:]])(wip|WIP)(|[^[:alnum:]]*) ]]; then
      res+=" ${modified}wip"
    fi

    # Format like starship (ahead/behind inside brackets or together)
    local ahead_behind=""
    (( VCS_STATUS_COMMITS_BEHIND )) && ahead_behind+="⇣${VCS_STATUS_COMMITS_BEHIND}"
    (( VCS_STATUS_COMMITS_AHEAD  )) && ahead_behind+="⇡${VCS_STATUS_COMMITS_AHEAD}"
    
    local status_str=""
    (( VCS_STATUS_STASHES        )) && status_str+="*${VCS_STATUS_STASHES}"
    [[ -n $VCS_STATUS_ACTION     ]] && status_str+="${VCS_STATUS_ACTION}"
    (( VCS_STATUS_NUM_CONFLICTED )) && status_str+="~${VCS_STATUS_NUM_CONFLICTED}"
    (( VCS_STATUS_NUM_STAGED     )) && status_str+="+${VCS_STATUS_NUM_STAGED}"
    (( VCS_STATUS_NUM_UNSTAGED   )) && status_str+="!${VCS_STATUS_NUM_UNSTAGED}"
    (( VCS_STATUS_NUM_UNTRACKED  )) && status_str+="?${VCS_STATUS_NUM_UNTRACKED}"
    (( VCS_STATUS_HAS_UNSTAGED == -1 )) && status_str+="─"

    if [[ -n $status_str || -n $ahead_behind ]]; then
        res+=" [${status_str}${ahead_behind}]"
    fi

    typeset -g my_git_format=$res
  }
  functions -M my_git_formatter 2>/dev/null

  typeset -g POWERLEVEL9K_VCS_MAX_INDEX_SIZE_DIRTY=-1
  typeset -g POWERLEVEL9K_VCS_DISABLED_WORKDIR_PATTERN='~'
  typeset -g POWERLEVEL9K_VCS_DISABLE_GITSTATUS_FORMATTING=true
  typeset -g POWERLEVEL9K_VCS_CONTENT_EXPANSION='${$((my_git_formatter()))+${my_git_format}}'
  typeset -g POWERLEVEL9K_VCS_{STAGED,UNSTAGED,UNTRACKED,CONFLICTED,COMMITS_AHEAD,COMMITS_BEHIND}_MAX_NUM=-1
  typeset -g POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_EXPANSION=
  typeset -g POWERLEVEL9K_VCS_BACKENDS=(git)

  ################################# Language Definitions #################################
  # node_version
  typeset -g POWERLEVEL9K_NODE_VERSION_FOREGROUND=$fg0
  typeset -g POWERLEVEL9K_NODE_VERSION_BACKGROUND=$blue
  typeset -g POWERLEVEL9K_NODE_VERSION_PROJECT_ONLY=true
  typeset -g POWERLEVEL9K_NODE_VERSION_VISUAL_IDENTIFIER_EXPANSION=''

  # c / cpp 
  typeset -g POWERLEVEL9K_C_FOREGROUND=$fg0
  typeset -g POWERLEVEL9K_C_BACKGROUND=$blue
  typeset -g POWERLEVEL9K_C_VISUAL_IDENTIFIER_EXPANSION=''
  typeset -g POWERLEVEL9K_CPP_FOREGROUND=$fg0
  typeset -g POWERLEVEL9K_CPP_BACKGROUND=$blue
  typeset -g POWERLEVEL9K_CPP_VISUAL_IDENTIFIER_EXPANSION=''

  # rust_version
  typeset -g POWERLEVEL9K_RUST_VERSION_FOREGROUND=$fg0
  typeset -g POWERLEVEL9K_RUST_VERSION_BACKGROUND=$blue
  typeset -g POWERLEVEL9K_RUST_VERSION_PROJECT_ONLY=true
  typeset -g POWERLEVEL9K_RUST_VERSION_VISUAL_IDENTIFIER_EXPANSION=''

  # go_version
  typeset -g POWERLEVEL9K_GO_VERSION_FOREGROUND=$fg0
  typeset -g POWERLEVEL9K_GO_VERSION_BACKGROUND=$blue
  typeset -g POWERLEVEL9K_GO_VERSION_PROJECT_ONLY=true
  typeset -g POWERLEVEL9K_GO_VERSION_VISUAL_IDENTIFIER_EXPANSION=''

  # php_version
  typeset -g POWERLEVEL9K_PHP_VERSION_FOREGROUND=$fg0
  typeset -g POWERLEVEL9K_PHP_VERSION_BACKGROUND=$blue
  typeset -g POWERLEVEL9K_PHP_VERSION_PROJECT_ONLY=true
  typeset -g POWERLEVEL9K_PHP_VERSION_VISUAL_IDENTIFIER_EXPANSION=''

  # java_version
  typeset -g POWERLEVEL9K_JAVA_VERSION_FOREGROUND=$fg0
  typeset -g POWERLEVEL9K_JAVA_VERSION_BACKGROUND=$blue
  typeset -g POWERLEVEL9K_JAVA_VERSION_PROJECT_ONLY=true
  typeset -g POWERLEVEL9K_JAVA_VERSION_VISUAL_IDENTIFIER_EXPANSION=''

  # kotlin_version
  typeset -g POWERLEVEL9K_KOTLIN_VERSION_FOREGROUND=$fg0
  typeset -g POWERLEVEL9K_KOTLIN_VERSION_BACKGROUND=$blue
  typeset -g POWERLEVEL9K_KOTLIN_VERSION_VISUAL_IDENTIFIER_EXPANSION=''

  # haskell_stack
  typeset -g POWERLEVEL9K_HASKELL_STACK_FOREGROUND=$fg0
  typeset -g POWERLEVEL9K_HASKELL_STACK_BACKGROUND=$blue
  typeset -g POWERLEVEL9K_HASKELL_STACK_SOURCES=(shell local)
  typeset -g POWERLEVEL9K_HASKELL_STACK_ALWAYS_SHOW=true
  typeset -g POWERLEVEL9K_HASKELL_STACK_VISUAL_IDENTIFIER_EXPANSION=''

  # python (Using pyenv / asdf styling for python module)
  typeset -g POWERLEVEL9K_PYTHON_FOREGROUND=$fg0
  typeset -g POWERLEVEL9K_PYTHON_BACKGROUND=$blue
  typeset -g POWERLEVEL9K_PYTHON_VISUAL_IDENTIFIER_EXPANSION=''
  
  # ASDF Python fallback
  typeset -g POWERLEVEL9K_ASDF_PYTHON_FOREGROUND=$fg0
  typeset -g POWERLEVEL9K_ASDF_PYTHON_BACKGROUND=$blue
  typeset -g POWERLEVEL9K_ASDF_PYTHON_VISUAL_IDENTIFIER_EXPANSION=''

  ################################ Contexts ################################
  # docker_context
  typeset -g POWERLEVEL9K_DOCKER_CONTEXT_FOREGROUND='#83a598'
  typeset -g POWERLEVEL9K_DOCKER_CONTEXT_BACKGROUND=$bg3
  typeset -g POWERLEVEL9K_DOCKER_CONTEXT_VISUAL_IDENTIFIER_EXPANSION=''

  # conda (anaconda)
  typeset -g POWERLEVEL9K_ANACONDA_FOREGROUND='#83a598'
  typeset -g POWERLEVEL9K_ANACONDA_BACKGROUND=$bg3
  typeset -g POWERLEVEL9K_ANACONDA_CONTENT_EXPANSION='${${${${CONDA_PROMPT_MODIFIER#\(}% }%\)}:-${CONDA_PREFIX:t}}'

  ####################################[ time: current time ]####################################
  typeset -g POWERLEVEL9K_TIME_FOREGROUND=$fg0
  typeset -g POWERLEVEL9K_TIME_BACKGROUND=$bg1
  typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M}'
  typeset -g POWERLEVEL9K_TIME_UPDATE_ON_COMMAND=false
  typeset -g POWERLEVEL9K_TIME_VISUAL_IDENTIFIER_EXPANSION=''


  # Transient prompt works similarly to the builtin transient_rprompt option.
  typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=always

  # Instant prompt mode.
  typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

  # Hot reload
  typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=true

  # If p10k is already loaded, reload configuration.
  (( ! $+functions[p10k] )) || p10k reload
}

# Tell `p10k configure` which file it should overwrite.
typeset -g POWERLEVEL9K_CONFIG_FILE=${${(%):-%x}:a}

(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'
